//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBERP1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERD
    {
        public string ID { get; set; }
        public string OMID { get; set; }
        public string PID { get; set; }
        public string PNAME { get; set; }
        public decimal OPRICE { get; set; }
        public Nullable<decimal> ONUM { get; set; }
        public Nullable<decimal> OMONEY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
